#!/bin/bash -l
#SBATCH --nodes=1 --ntasks-per-node=1
#SBATCH -t 00:25:00
#SBATCH -o slurm.%N.%j.o
#SBATCH -e slurm.%N.%j.e
#SBATCH --mail-user=jaewon_lee@ucsb.edu
#SBATCH --mail-type=end
#  Asking for 1 node with 1 cores

cd $SLURM_SUBMIT_DIR

module load intel/20

ulimit -s unlimited

/bin/hostname
mpirun -np $SLURM_NTASKS  /home/fuz/vasp/6.3.2/bin/vasp_std > out-jwl

